CREATE TABLE Role (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE User (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) NOT NULL,
firstName VARCHAR(255),
lastName VARCHAR(255),
password VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
roleId INT,
UNIQUE (username),
UNIQUE (email),
FOREIGN KEY (roleId) REFERENCES Role(id)
);

INSERT INTO Role (name) VALUES ('STUDENT'), ('APPRENTICE'), ('TEACHER'), ('ADMIN');
